# Làm sạch dữ liệu CareerViet

## 1. Đọc dữ liệu

In [1]:
import pandas as pd
import ast
import os
import numpy as np

df_raw = pd.read_csv('../dataset/careerviet_updated_jobs.csv')

print(df_raw.shape)
print(f'\nCột:\n{list(df_raw.columns)}')

(23536, 40)

Cột:
['job_id', 'job_title', 'emp_id', 'emp_name', 'job_salary_unit', 'job_active_date', 'job_contact_hide', 'location_name_en', 'location_name', 'job_is_urgent_job', 'job_competition', 'top_industries', 'emp_logo', 'job_check_profile', 'job_eoc', 'job_last_date', 'date_view', 'job_experience', 'job_to_experience', 'benefit_id', 'benefit_icon', 'benefit_name_en', 'benefit_name_vn', 'jobEoc', 'url_emp_default', 'prize_name', 'job_class_css_item', 'job_link', 'job_salary_string', 'job_new', 'job_title_red', 'job_premium_icon_item', 'has_save_job', 'premium_industries', 'district_id', 'industries', 'url_logo_emp_eoc', 'emp_eoc_active', 'job_from_salary', 'job_to_salary']

In [2]:
df_raw.head().T

,0,1,2,3,4
job_id,35C6E948,35C6BFD8,35C6B7D2,35C71B2E,35C71809
job_title,Nhân Viên Phòng Nghiệp Vụ,Senior Security Network Engineer,Bảo Vệ,Chuyên viên Cao cấp Xử lý nợ,CCTV Manager
emp_id,35AA1BAF,35A828EC,35AA1DD7,35A6ADCB,35A4FED8
emp_name,Công Ty TNHH Dịch Vụ Bảo Vệ Đại Trường Hải,Techtronic Industries Vietnam Manufacturing Co...,CÔNG TY CỔ PHẦN WEI XERN SIN VIỆT NAM,Ngân Hàng TMCP Quốc Tế Việt Nam,Masan Consumer
job_salary_unit,vnd,ltt,vnd,vnd,vnd
job_active_date,2026-03-27T03:10:13.654Z,2026-03-11T06:28:56.381Z,2026-03-09T04:18:00.567Z,2026-04-14T10:20:59.527Z,2026-04-13T14:00:58.821Z
job_contact_hide,0,0,0,0,0
location_name_en,"[""Ho Chi Minh""]","[""Ho Chi Minh""]","[""Da Nang""]","[""Ba Ria-VT"", "" Dong Nai"", "" Binh Duong""]","[""Ho Chi Minh""]"
location_name,"[""Hồ Chí Minh""]","[""Hồ Chí Minh""]","[""Đà Nẵng""]","[""Bà Rịa - Vũng Tàu"", "" Đồng Nai"", "" Bình Dương""]","[""Hồ Chí Minh""]"
job_is_urgent_job,1,0,1,0,0
job_competition,1,1,1,1,1
top_industries,[51],[51],[],[24],[]
emp_logo,https://images.careerviet.vn/employer_folders/...,https://images.careerviet.vn/employer_folders/...,https://images.careerviet.vn/employer_folders/...,https://images.careerviet.vn/employer_folders/...,https://images.careerviet.vn/employers/5592/14...
job_check_profile,1,1,1,1,1
job_eoc,0,1,0,0,1
job_last_date,2026-05-26T03:10:13.654Z,2026-05-10T06:28:56.380Z,2026-05-08T04:18:00.566Z,2026-05-20T00:00:00.000Z,2026-05-13T00:00:00.000Z
date_view,2026-04-28T02:00:22.972Z,2026-04-10T22:00:46.354Z,2026-04-28T01:30:18.926Z,2026-04-27T20:02:22.783Z,2026-04-26T20:02:18.321Z
job_experience,0.0,3.0,NaN,1.0,3.0
job_to_experience,1.0,5.0,NaN,5.0,5.0
benefit_id,"[2, 3, 8, 9, 10, 11]","[1, 2, 5, 7, 8, 9, 11, 13, 14]",[],"[2, 3, 8, 9, 10, 11]","[2, 3, 8, 9, 10, 11]"
benefit_icon,"[""fa-medkit"", ""fa-plane"", ""fa-usd"", ""fa-user-m...","[""fa-laptop"", ""fa-medkit"", ""fa-taxi"", ""fa-blac...",[],"[""fa-medkit"", ""fa-plane"", ""fa-usd"", ""fa-user-m...","[""fa-medkit"", ""fa-plane"", ""fa-usd"", ""fa-user-m..."
benefit_name_en,"[""Insurance"", ""Travel"", ""Incentive bonus"", ""He...","[""Laptop"", ""Insurance"", ""Employee Shuttle"", ""U...",[],"[""Insurance"", ""Travel"", ""Incentive bonus"", ""He...","[""Insurance"", ""Travel"", ""Incentive bonus"", ""He..."
benefit_name_vn,"[""Chế độ bảo hiểm"", ""Du Lịch"", ""Chế độ thưởng""...","[""Laptop"", ""Chế độ bảo hiểm"", ""Xe đưa đón"", ""Đ...",[],"[""Chế độ bảo hiểm"", ""Du Lịch"", ""Chế độ thưởng""...","[""Chế độ bảo hiểm"", ""Du Lịch"", ""Chế độ thưởng""..."
jobEoc,0.0,1.0,0.0,0.0,1.0
url_emp_default,/en/nha-tuyen-dung/cong-ty-tnhh-dich-vu-bao-ve...,/en/nha-tuyen-dung/techtronic-industries-vietn...,/en/nha-tuyen-dung/cong-ty-co-phan-wei-xern-si...,/en/nha-tuyen-dung/ngan-hang-tmcp-quoc-te-viet...,/en/nha-tuyen-dung/masan-consumer.35A4FED8.html
prize_name,NaN,Top EOC - Doanh Nghiệp Lớn,NaN,NaN,Top EOC - Doanh Nghiệp Lớn
job_class_css_item,has-background bg-urgent-job has-background,has-background has-premium,has-background bg-urgent-job,NaN,NaN
job_link,https://careerviet.vn/en/tim-viec-lam/nhan-vie...,https://careerviet.vn/en/tim-viec-lam/senior-s...,https://careerviet.vn/en/tim-viec-lam/bao-ve.3...,https://careerviet.vn/en/tim-viec-lam/chuyen-v...,https://careerviet.vn/en/tim-viec-lam/cctv-man...
job_salary_string,Competition,Competition,Competition,Competition,Competition
job_new,0,0,0,0,0
job_title_red,is-red,is-red,is-red,is-red,is-red
job_premium_icon_item,0,1,0,0,0
has_save_job,0,0,0,0,0
premium_industries,[],[],[],[],[]
district_id,[],[],[],[],[]
industries,"[""51"", ""9"", ""4""]","[""1"", ""63"", ""51""]","[""54"", ""51"", ""8""]","[""19"", ""24"", ""51""]","[""51""]"
url_logo_emp_eoc,NaN,https://images.careerviet.vn/empofchoice/17605...,NaN,NaN,https://images.careerviet.vn/empofchoice/17605...
emp_eoc_active,NaN,1.0,NaN,NaN,1.0
job_from_salary,NaN,NaN,NaN,NaN,NaN
job_to_salary,NaN,NaN,NaN,NaN,NaN

## 2. Lọc các cột

Giữ lại các cột cần thiết

In [4]:
job_field_mapping = {
    "job_id": "mã công việc",
    "job_title": "tên công việc",
    "emp_id": "mã công ty",
    "emp_name": "tên công ty",
    "job_salary_unit": "đơn vị tiền tệ",
    "location_name": "địa điểm",
    "job_is_urgent_job": "khẩn cấp",
    "job_competition": "lương cạnh tranh",
    "job_eoc": "công ty yêu thích",
    "job_last_date": "hạn nộp",
    "date_view": "ngày cập nhật",
    "job_experience": "kinh nghiệm từ (năm)",
    "job_to_experience": "kinh nghiệm đến (năm)",
    "benefit_name_vn": "phúc lợi",
    "industries": "ngành",
    "job_from_salary": "lương từ",
    "job_to_salary": "lương đến"
}

# Loc cac cot ton tai trong du lieu goc
filter_cols = [c for c in job_field_mapping.keys() if c in df_raw.columns]

# if cot_thieu:
#     print(f'Cac cot khong tim thay trong du lieu goc: {cot_thieu}')

# Tao DataFrame moi chi voi cac cot can thiet
df = df_raw[filter_cols].copy()

print(df.shape)
display(df.head().T)

(23536, 17)

,0,1,2,3,4
job_id,35C6E948,35C6BFD8,35C6B7D2,35C71B2E,35C71809
job_title,Nhân Viên Phòng Nghiệp Vụ,Senior Security Network Engineer,Bảo Vệ,Chuyên viên Cao cấp Xử lý nợ,CCTV Manager
emp_id,35AA1BAF,35A828EC,35AA1DD7,35A6ADCB,35A4FED8
emp_name,Công Ty TNHH Dịch Vụ Bảo Vệ Đại Trường Hải,Techtronic Industries Vietnam Manufacturing Co...,CÔNG TY CỔ PHẦN WEI XERN SIN VIỆT NAM,Ngân Hàng TMCP Quốc Tế Việt Nam,Masan Consumer
job_salary_unit,vnd,ltt,vnd,vnd,vnd
location_name,"[""Hồ Chí Minh""]","[""Hồ Chí Minh""]","[""Đà Nẵng""]","[""Bà Rịa - Vũng Tàu"", "" Đồng Nai"", "" Bình Dương""]","[""Hồ Chí Minh""]"
job_is_urgent_job,1,0,1,0,0
job_competition,1,1,1,1,1
job_eoc,0,1,0,0,1
job_last_date,2026-05-26T03:10:13.654Z,2026-05-10T06:28:56.380Z,2026-05-08T04:18:00.566Z,2026-05-20T00:00:00.000Z,2026-05-13T00:00:00.000Z
date_view,2026-04-28T02:00:22.972Z,2026-04-10T22:00:46.354Z,2026-04-28T01:30:18.926Z,2026-04-27T20:02:22.783Z,2026-04-26T20:02:18.321Z
job_experience,0.0,3.0,NaN,1.0,3.0
job_to_experience,1.0,5.0,NaN,5.0,5.0
benefit_name_vn,"[""Chế độ bảo hiểm"", ""Du Lịch"", ""Chế độ thưởng""...","[""Laptop"", ""Chế độ bảo hiểm"", ""Xe đưa đón"", ""Đ...",[],"[""Chế độ bảo hiểm"", ""Du Lịch"", ""Chế độ thưởng""...","[""Chế độ bảo hiểm"", ""Du Lịch"", ""Chế độ thưởng""..."
industries,"[""51"", ""9"", ""4""]","[""1"", ""63"", ""51""]","[""54"", ""51"", ""8""]","[""19"", ""24"", ""51""]","[""51""]"
job_from_salary,NaN,NaN,NaN,NaN,NaN
job_to_salary,NaN,NaN,NaN,NaN,NaN

## 3. Đổi tên cột sang tiếng Việt

In [5]:

new_cols = {k: v for k, v in job_field_mapping.items() if k in filter_cols}
df = df.rename(columns=new_cols)

for cot in df.columns:
    print(f'  - {cot}')

df.to_csv('../dataset/careerviet_all_jobs_renamed.csv', index=False, encoding='utf-8-sig')

df.head()

  - mã công việc
  - tên công việc
  - mã công ty
  - tên công ty
  - đơn vị tiền tệ
  - địa điểm
  - khẩn cấp
  - lương cạnh tranh
  - công ty yêu thích
  - hạn nộp
  - ngày cập nhật
  - kinh nghiệm từ (năm)
  - kinh nghiệm đến (năm)
  - phúc lợi
  - ngành
  - lương từ
  - lương đến

,mã công việc,tên công việc,mã công ty,tên công ty,đơn vị tiền tệ,địa điểm,khẩn cấp,lương cạnh tranh,công ty yêu thích,hạn nộp,ngày cập nhật,kinh nghiệm từ (năm),kinh nghiệm đến (năm),phúc lợi,ngành,lương từ,lương đến
0,35C6E948,Nhân Viên Phòng Nghiệp Vụ,35AA1BAF,Công Ty TNHH Dịch Vụ Bảo Vệ Đại Trường Hải,vnd,"[""Hồ Chí Minh""]",1,1,0,2026-05-26T03:10:13.654Z,2026-04-28T02:00:22.972Z,0.0,1.0,"[""Chế độ bảo hiểm"", ""Du Lịch"", ""Chế độ thưởng""...","[""51"", ""9"", ""4""]",NaN,NaN
1,35C6BFD8,Senior Security Network Engineer,35A828EC,Techtronic Industries Vietnam Manufacturing Co...,ltt,"[""Hồ Chí Minh""]",0,1,1,2026-05-10T06:28:56.380Z,2026-04-10T22:00:46.354Z,3.0,5.0,"[""Laptop"", ""Chế độ bảo hiểm"", ""Xe đưa đón"", ""Đ...","[""1"", ""63"", ""51""]",NaN,NaN
2,35C6B7D2,Bảo Vệ,35AA1DD7,CÔNG TY CỔ PHẦN WEI XERN SIN VIỆT NAM,vnd,"[""Đà Nẵng""]",1,1,0,2026-05-08T04:18:00.566Z,2026-04-28T01:30:18.926Z,NaN,NaN,[],"[""54"", ""51"", ""8""]",NaN,NaN
3,35C71B2E,Chuyên viên Cao cấp Xử lý nợ,35A6ADCB,Ngân Hàng TMCP Quốc Tế Việt Nam,vnd,"[""Bà Rịa - Vũng Tàu"", "" Đồng Nai"", "" Bình Dương""]",0,1,0,2026-05-20T00:00:00.000Z,2026-04-27T20:02:22.783Z,1.0,5.0,"[""Chế độ bảo hiểm"", ""Du Lịch"", ""Chế độ thưởng""...","[""19"", ""24"", ""51""]",NaN,NaN
4,35C71809,CCTV Manager,35A4FED8,Masan Consumer,vnd,"[""Hồ Chí Minh""]",0,1,1,2026-05-13T00:00:00.000Z,2026-04-26T20:02:18.321Z,3.0,5.0,"[""Chế độ bảo hiểm"", ""Du Lịch"", ""Chế độ thưởng""...","[""51""]",NaN,NaN

## 4. Kiểm tra dữ liệu

In [13]:
import pandas as pd
import numpy as np

# Tạo bản sao để thao tác an toàn
df_processed = df.copy()

# 1. Chuyển đổi các chuỗi mang ý nghĩa "trống" thành giá trị NaN thực sự của Pandas
# Regex này sẽ quét và thay thế:
# - Chuỗi "[]" hoặc có chứa khoảng trắng bên trong như "[ ]"
# - Chuỗi "null" (nếu có do lỗi JSON parsing)
# - Chuỗi rỗng "" hoặc chỉ chứa dấu cách
df_processed = df_processed.replace(r'^\s*\[\s*\]\s*$|^\s*null\s*$|^\s*$', np.nan, regex=True)

# 2. Tính số lượng thiếu (lúc này isnull() đã nhận diện được chính xác)
missing_values_count = df_processed.isnull().sum()

# 3. Tính tỉ lệ phần trăm (%) thiếu thông tin
missing_ratio_percent = df_processed.isnull().mean() * 100

# 4. Gộp kết quả thành bảng cho dễ nhìn
missing_info = pd.DataFrame({
    'Số lượng thiếu': missing_values_count,
    'Tỉ lệ thiếu (%)': missing_ratio_percent
})

# Lọc ra các cột có dữ liệu thiếu (Tỉ lệ > 0) và sắp xếp giảm dần
missing_info = missing_info[missing_info['Số lượng thiếu'] > 0].sort_values(by='Tỉ lệ thiếu (%)', ascending=False)

print(missing_info)

                       Số lượng thiếu  Tỉ lệ thiếu (%)
lương đến                       10713        45.517505
lương từ                        10713        45.517505
kinh nghiệm đến (năm)            6989        29.694935
kinh nghiệm từ (năm)             4009        17.033481
ngành                            1000         4.248810
phúc lợi                          501         2.128654
mã công ty                        258         1.096193

## 5. Explode các trường có nhiều giá trị

In [14]:
def parse_list_field(value):
    """
    Chuyen doi gia tri dang chuoi danh sach thanh list Python.
    Vi du: '["Ho Chi Minh", " Binh Duong"]' -> ['Ho Chi Minh', 'Binh Duong']
    """
    if pd.isna(value):
        return []
    
    value_str = str(value).strip()
    
    # Truong hop chuoi rong hoac khong phai danh sach
    if value_str == '' or value_str == '[]':
        return []
    
    try:
        # Thu parse bang ast.literal_eval
        parsed = ast.literal_eval(value_str)
        if isinstance(parsed, list):
            # Loai bo khoang trang thua o dau va cuoi moi phan tu
            return [str(item).strip() for item in parsed if str(item).strip()]
        else:
            return [str(parsed).strip()]
    except (ValueError, SyntaxError):
        # Neu khong parse duoc, giu nguyen gia tri goc
        return [value_str.strip()]

In [15]:
# Danh sach cac cot can tach (co dang danh sach nhieu gia tri)
multi_value_columns = ['địa điểm', 'phúc lợi', 'ngành']

In [16]:
# Parse cac truong dang danh sach
df_clean = df.copy()

for cot in multi_value_columns:
    df_clean[cot] = df_clean[cot].apply(parse_list_field)

# Xem ket qua parse
print(df_clean['địa điểm'].head().tolist())

[['Hồ Chí Minh'], ['Hồ Chí Minh'], ['Đà Nẵng'], ['Bà Rịa - Vũng Tàu', 'Đồng Nai', 'Bình Dương'], ['Hồ Chí Minh']]

In [18]:
# Tạo một dictionary để chứa các DataFrame mới
# Ví dụ: dataframes_exploded['industries'] sẽ trả về DataFrame chỉ explode cột industries
dataframes_exploded = {}

print(f'Số dòng ban đầu của df_clean: {len(df_clean)}\n')

for cot in multi_value_columns:
    # 1. Tạo một bản sao từ DataFrame "gốc" (df_clean) cho mỗi vòng lặp
    df_temp = df_clean.copy()
    
    # 2. Xử lý các list rỗng (thay bằng mảng chứa chuỗi rỗng để không mất dòng)
    df_temp[cot] = df_temp[cot].apply(lambda x: x if isinstance(x, list) and len(x) > 0 else [''])
    
    # 3. Tách dòng (explode)
    df_temp = df_temp.explode(cot, ignore_index=True)
    
    # 4. Xóa khoảng trắng dư thừa
    df_temp[cot] = df_temp[cot].astype(str).str.strip()
    
    # 5. Lưu DataFrame mới vào dictionary
    dataframes_exploded[cot] = df_temp
    
    print(f'Done explode cột: {cot}')

df_mapping_industries = pd.read_csv('../dataset/careerviet_industries.csv')
mapping_dict = dict(zip(df_mapping_industries['industry_id'].astype(str), df_mapping_industries['industry_name_vn']))


for cot, df_exploded in dataframes_exploded.items():
    # print(f'\n=== DataFrame sau khi explode cột: {cot} ===')
    # print(df_exploded.head())
    
    if cot == "ngành":
        # Thay thế mã ngành bằng tên ngành
        df_exploded[cot] = df_exploded[cot].map(mapping_dict).fillna(df_exploded[cot])
    
    df_exploded.to_csv(f'../dataset/exploded_{cot}.csv', index=False)

Số dòng ban đầu của df_clean: 23536

Done explode cột: địa điểm
Done explode cột: phúc lợi
Done explode cột: ngành